

service: myserverlessprojectchecking

frameworkVersion: "3"

#deploy into lambda
provider:
  name: aws
  runtime: nodejs18.x
  profile: serverlessUserRadha
  environment:
        tableName: ${self:custom.tableName}
        bucketName: ${self:custom.bucketName}
  iamRoleStatements:
        - Effect: Allow
          Action:
              - dynamodb:*
              - s3:*
          Resource: '*'
  

plugins:
  - serverless-s3-sync
  - serverless-webpack
package:
  individually: true  

custom:
  tableName: checking-table
  bucketName: serverless-user-radha-project-123
  s3Sync:
     - bucketName:  ${self:custom.bucketName}
       localDir: UploadData  

functions:
  getUser:
    handler: lambda/endpoints/getUser.handler
    events:
        - http:
             path: get-user/{ID}
             method: GET
             cors: true

  getUserAge:
    handler: lambda/endpoints/getUserAge.handler
    events:
        - http:
             path: get-user-age/{ID}
             method: GET
             cors: true

  createUserData:
        handler: lambda/endpoints/createUserData.handler
        events:
            - http:
                  path: create-user-data/{ID}
                  method: POST
                  cors: true 

  createFile:
        handler: lambda/endpoints/createFile.handler
        events:
            - http:
                  path: create-file/{fileName}
                  method: POST
                  cors: true  

  getFile:
        handler: lambda/endpoints/getFile.handler
        events:
            - http:
                  path: get-file/{fileName}
                  method: GET
                  cors: true                                        


resources:
  Resources:
      DemoBucketUpload:
           Type: AWS::S3::Bucket
           Properties: 
              BucketName:  ${self:custom.bucketName}

      MyDynamoDbTable:
            Type: AWS::DynamoDB::Table
            Properties:
                TableName: ${self:custom.tableName}
                AttributeDefinitions:
                    - AttributeName: ID
                      AttributeType: S
                KeySchema:
                    - AttributeName: ID
                      KeyType: HASH
                BillingMode: PAY_PER_REQUEST        

